name: 'cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  clean_workflow_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: clean workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 30

  remove_package_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: ${{ github.event.repository.name }}
          org: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: org
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-owner: ${{ github.repository_owner }}
          package-name: ${{ github.event.repository.name }}
          delete-untagged: true

